name: Tests

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 6 * * 3"
  pull_request:
    branches: [ master ]

jobs:
  php-version:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: "${{ matrix.php-version }}"
            coverage: "pcov"
            ini-values: "zend.assertions=1"

        - name: Get Composer Cache Directory 2
          id: composer-cache
          run: |
            echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

        - uses: actions/cache@v4
          id: actions-cache
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-

        - name: Cache PHP dependencies
          uses: actions/cache@v4
          id: vendor-cache
          with:
            path: vendor
            key: ${{ runner.os }}-build-${{ hashFiles('**/composer.lock') }}

        - name: Install Composer dependencies
          run: composer install --no-progress --ansi

        - name: Code style test
          run: ./vendor/bin/phpcs

        - name: PHPStan code analysis
          run: php vendor/bin/phpstan analyze

        - name: Execute Rector
          run: vendor/bin/rector --dry-run

        - name: Run tests
          run: ./vendor/bin/phpunit --color=always --coverage-clover=coverage.xml ./test

        - name: Send code coverage report to Codecov.io
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: coverage.xml
